name: Publish @elastic-sonar-search/router-type
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci -w types
      - run: npm publish -w types --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
